/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/box.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/tree.vue')['default']
    TreeItem: typeof import('./src/components/treeItem.vue')['default']
  }
}
